name: teoria
type: web  # Defines the type of the application (e.g., web, worker)
env: node  # Specifies the runtime environment
buildCommand: npm install  # Command to install dependencies
startCommand: npm start  # Command to start the server


